[package]
name = "datis-cmd"
version = "2.2.2"
authors = ["Markus Ast <m@rkusa.st>"]
edition = "2018"

[dependencies]
clap = "2.32"
ctrlc = "3.1"
datis-core = { path = "../datis-core" }
dotenv = "0.15"
env_logger = "0.8"
log = "0.4"