[package]
name = "srs"
version = "2.2.0-beta.5"
authors = ["rkusa"]
edition = "2018"

[dependencies]
base64 = "0.13"
byteorder = "1.3"
bytes = "0.5"
futures = "0.3"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
thiserror = "1.0"
tokio = { version = "0.2", features = ["time", "udp", "tcp", "sync", "io-util"] }
tokio-util = { version = "0.3", features = ["codec", "udp"] }
uuid = { version = "0.8", features = ["v4"] }